#移客通
mutils:
  yiketong:
    environment: formal
    corp-key: 123123123
    corp-secret: awd123123
  #微信小程序
  wechat:
    miniprogram:
      app-secret: 小程序
      appid: 小程序
    #微信支付
    pay:
      enable: true
      partner-id: 商户号
      certificate-path: 证书地址
      refund-notify-url: 退款回调地址
      partner-key: 商户id
      notify-url: 支付回调地址
    #微信app
    app:
      app-secret: app
      appid: app
    #微信公众号
    jsapi:
      app-secret: 公众号
      appid: 公众号
  meituan:
    peisong:
      config:
        test:
          app-key: test
          secret: 123123
        formal:
          app-key: test
          secret: 123123
      config-prefix: test
  #快递100
  kuaidi100:
    customer: 123123
    key: 123123
    url: 123123123123
  #个推
  gexin:
    push:
      config:
        test:
          appid: 配置1
          appkey: 配置1
          master-secret: 配置1
        test2:
          appid: 配置2
          appkey: 配置2
          master-secret: 配置2

